# Numpy Tutorial

In [1]:
#create a numpy array:

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# numpy = numerical python
# array in numpy is called ndarray


In [3]:
# numpy array is 50x faster than traditional python lists.
# array is very frequently used in data science where speed and resources are very important

In [4]:
# 0-D arrays
arr1 = np.array(42)
print(arr1)

42


In [5]:
#1-d array
arr2 = np.array([1,2,3,4])
print(arr2)

[1 2 3 4]


In [7]:
#2d array
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [8]:
#3d arrays
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [9]:
#checking dimensions
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [11]:
#higher dimensions array
arr5 = np.array([1,2,3,4],ndmin=5)
print(arr5)
print(arr5.ndim)

[[[[[1 2 3 4]]]]]
5


# array indexing

In [14]:
# first element
arr[0]

1

In [13]:
#second element
arr[1]

2

In [15]:
#adding third and fourth element
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [16]:
# access 2-d arrays
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3[0,1])

2


In [19]:
print(arr3[1,2])

6


In [20]:
# access 3-d array
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr4[0,1,1])

5


In [21]:
# negative indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,-1]

10

# numpy array slicing


In [22]:
#[start:end:step]

In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7 8 9]
[1 2 3 4]
[7 8]
[2 4]
[1 3 5 7 9]


In [26]:
# slicing 2d array

In [32]:
arr1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr1[1,1:4])
print(arr1[0:2, 2])
print(arr1[0:2, 1:4])

[ 8  9 10]
[3 9]
[[ 2  3  4]
 [ 8  9 10]]


# Numpy DataTypes

In [33]:
#checking the datatype of array object
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [34]:
arr1 = np.array(['apple','banana'])
arr1.dtype

dtype('<U6')

In [35]:
# creating array with defined datatypes
arr = np.array([1,2,3,4],dtype='S')
arr.dtype

dtype('S1')

In [36]:
arr1 = np.array([1,2,3,4,5],dtype='i4')
arr1.dtype

dtype('int32')

In [41]:
arr = np.array([1.1,1.2,0.3])
newarr = arr.astype('i')
newarr.dtype
newarr

array([1, 1, 0], dtype=int32)

In [42]:
newarr1 = arr.astype(bool)
newarr1

array([ True,  True,  True])

In [43]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)
newarr

array([ True, False,  True])