# Scikit Learn

In [4]:
!pip install scikit-learn


  Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   - -------------------------------------- 1.6/41.0 MB 8.4 MB/s eta 0:00:05
   --- ------------------------------------ 3.1/41.0 MB 8.0 MB/s eta 0:00:05
   ---- ----------------------------------- 4.2/41.0 MB 7.2 MB/s eta 0:00:06
   ----- ---------------------------------- 6.0/41.0 MB 7.5 MB/s eta 0:00:05
   -------- ------------------------------- 8.4/41.0 MB 8.3 MB/s eta 0:00:04
   --------- ------------------------------ 9.7/41.0 MB 8.0 MB/s eta 0:00:04
   ---------- ----------------------------- 10.7/41.0 MB 8.1 MB/s eta 0:00:04
   ----------- ---------------------------- 11.8/41.0 MB 7.3 MB/s eta 0:00:04
   ------------- -------------------------- 13.6/41.0 MB 7.6 MB/s eta 0:00:04
   -------------- --


[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
from sklearn import datasets
iris = datasets.load_iris()
digit = datasets.load_digits()

In [12]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
digit.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

# Learning and Predicting

In [14]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100)

In [15]:
clf

SVC(C=100, gamma=0.001)

In [17]:
clf.fit(digit.data[:-1],digit.target[:-1])

SVC(C=100, gamma=0.001)

In [18]:
clf.predict(digit.data[-1:])

array([8])

# typecasting


In [25]:
import numpy as np
from sklearn import kernel_approximation

rng = np.random.RandomState(0)
X = rng.rand(10,200)
print(X.dtype)
X = np.array(X,dtype='float32')
print(X.dtype)

transformer = kernel_approximation.RBFSampler()
X_new = transformer.fit_transform(X)
X_new.dtype

float64
float32


dtype('float32')

In [26]:
from sklearn import datasets
from sklearn.svm import SVC

iris = datasets.load_iris()
clf = SVC()
clf.fit(iris.data,iris.target)

SVC()

In [29]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [30]:
clf.fit(iris.data,iris.target_names[iris.target])

SVC()

In [31]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']