## Tensor 


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#rank_0_tensor also called scalar contains single value  and no axes
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#rank_1_tesnor also called vector contains list of values. A vector has axes

In [5]:
rank_1_tensor = tf.constant([1,2,3,4])
rank_1_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [6]:
#rank_2_tensor also called matrix contains 2d array or two axes
rank_2_tensor = tf.constant([[1,2],[3,4]],dtype=tf.float32)

In [7]:
rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [8]:
#rank_3_tensor - more than 2 axes
rank_3_tensor = tf.constant([[[1,2,3,4,5],[5,2,3,1,4]],[[21,4,1,2,4],[2,3,3,3,3]]])

In [9]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 5,  2,  3,  1,  4]],

       [[21,  4,  1,  2,  4],
        [ 2,  3,  3,  3,  3]]])>

In [10]:
#you can convert tensor into numpy array
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [11]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [12]:
# the base tensor require it to be rectangular but if we have irregular shapes we can use ragged tensor and sparse tensor

In [13]:
ragged_list = [[

    [1,2,3,4],
    [0,1],
    [5,6,7],
    [9]
]]

try:
    tensor = tf.constant(ragged_list) #throws an error
except Exception as e:
    print(f"type(e).__name__:{e}")
    
    

type(e).__name__:Can't convert non-rectangular Python sequence to Tensor.


In [14]:
#Now use tf.ragged.RaggedTensor
ragged_tensor = tf.ragged.constant(ragged_list)

In [15]:
ragged_tensor

<tf.RaggedTensor [[[1, 2, 3, 4], [0, 1], [5, 6, 7], [9]]]>

In [17]:
ragged_tensor.shape

TensorShape([1, None, None])